server:
  port: 8081
spring:
  application:
   name: vlep-business

  redis:
    pool:
      max-active: 2000
      max-idle: 500
      min-idle: 50
      max-wait: 100000
    timeout: 3000
    host: localhost
    port: 6379
    database: 0

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vlep?characterEncoding=UTF-8&useSSL=false
    hikari:
      read-only: false
      connection-test-query: SELECT 1
      connection-timeout: 60000
      validation-timeout: 3000
      maximum-pool-size: 50

mybatis:
  type-aliases-package: com.anji.allways.entity
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.anji.allways.dao: debug


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/