spring:
  application:
   name: vlep-business
  redis:
    pool:
      max-active: 2000
      max-idle: 500
      min-idle: 50
      max-wait: 100000
    timeout: 3000
    host: localhost
    port: 6379
    database: 0
server:
  port: 8081
mybatis:
  type-aliases-package: com.anji.allways.entity
  mapper-locations: classpath:/mapper/*.xml